[package]
name = "japan-mesh"
version = "0.1.0"
authors = ["Kanahiro <mediterranean1769@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geojson = "0.19.0"
serde_json = "1.0.56"